### ISSUE TITLE
Fix edge values for Age Weight and Height on survey page

### ISSUE THREAD

**Issue by adrienguan2** [cse442-at-ub/project_s23-the-ai-violators#100]
**Task Tests**

_Test 1_

1. Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2. Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)
3. Here on the survey, you will be testing edge cases. To start, enter the following values in their respective fields: 21 for the age, Male for the sex, 72 for the height and 185 for the weight, Lose Weight/Cut for the fitness goal, proteins for the macros, lactose and glucose intolerance for the dietary restrictions. and active for the activity level. Do not click get started yet.
4. Change the age value to a value under 10, and attempt to hit the blue "Get Started" button. You should have a message pop up saying "Value must be greater than or equal to 10".

![age_low.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/192e7bd5-4f6c-4798-aed7-7c8b0c0cf238)

5. Change the age value to be over 99, and attempt to hit the blue "Get Started" button. You should have a message pop up saying "Value must be less than or equal to 99".

![age_high.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/bd9fff38-7f2d-4398-b01e-cf3540756a86)

6. Return the age value to a valid value (between 10 and 99) and then move onto the height field. Once here, change the height to be a value less than 20. Attempt to hit the blue "Get Started" button. You should have a message pop up saying "Value must be greater than or equal to 20".

![height_low.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/0b0c123f-b739-4b32-9143-2ad0f6df4e49)

7. Change the height value to a value over 110, and attempt to hit the blue "Get Started" button. You should have a message pop up saying "Value must be less than or equal to 110".

![height_hight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/bcfed430-977b-4abf-94a2-d023070068ea)

8. Return the height value to a valid value (between 20 and 110) and then move onto the weight field. Once here, change the weight to be a value less than 5. Attempt to hit the blue "Get Started" button. You should have a message pop up saying "Value must be greater than or equal to 5".

![weight_low.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/8082f7dd-13c5-400b-a245-2f7b23dff57f)

9. Change the weight value to a value over 1400, and attempt to hit the blue "Get Started" button. You should have a message pop up saying "Value must be less than or equal to 1400".
![weight_high.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/70d6f0aa-7116-4bf4-aa68-c9ee5023cab9)

10. If all of the messages mentioned above appeared as depicted, then this test passes and this task is complete.

**Comment by Nildham21** [comment]
Attach the survey page user story as dependency

**Comment by Nildham21** [comment]
This task should be bocking the user story, not the other way around, please fix that

**Comment by Nildham21** [comment]
Still need to address this: This task should be bocking the user story, not the other way around, please fix that
