### ISSUE TITLE
Fix survey page crashing with empty input fields

### ISSUE THREAD

**Issue by adrienguan2** [cse442-at-ub/project_s23-the-ai-violators#101]
**Task Tests** 

_Test 1_

1. Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2. Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

3. Here on the survey, you will be testing for an error where when the blue "Get started" button at the bottom of the page is pressed and all input fields are not filled in, an error screen will appear.  To start, click the blue "get started" button on the bottom of the page and take a look at the first input field at the top of the page asking for age. An error message similar to the one below should pop up requiring you to place input into this field. 

4. Fill in a proper value for the age input field (an error message will tell you if your input is invalid) then hit the "get started" button again. Now focus your attention the the field below that asks the sex. Another error box should pop up similar to how it did in step 3. It may not be exact, but as long as a box appears requiring you to select a value or input a value before the page redirects you, this step should pass.

5. Repeat steps 3 and 4 for the remaining input fields. This means leave the field to be tested blank, hit the "get started" button and ensure an error box appears. A few more examples of the messages you can get are pictured below, and as long as each input field receives an error box when left blank, this test passes and the task is complete. 

![sex_error.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/1f84af7b-b104-4979-ab54-c9ce82148dec)

![macrod.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/0b156d1d-fd2f-4c89-bc62-7b653f0a48e5)

**Comment by Nildham21** [comment]
Need to add task tests

**Comment by Nildham21** [comment]
Keep steps 1 and 2, after that for each step you should attempt to press the get started button and verify that an error message appears to indicate an input needs to be filled out. Give the value/ section that the user should enter for that input and then try the get started button again to verify the form does not get submitted until all the required input values are filled out

**Comment by Nildham21** [comment]
Attach this test to the Survey user story

**Comment by Nildham21** [comment]
Test 1 step 3, you can remove this line " an error screen appears instead of a pop up message being presented." it seems a bit confusing
