### ISSUE TITLE
Fix activity level description on survey page

### ISSUE THREAD

**Issue by adrienguan2** [cse442-at-ub/project_s23-the-ai-violators#103]
**Task Tests** 

_Test 1_

1. Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2. Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

3. Once on the survey, take a look at the bottom of the page at the "activity level" field. Ensure that it looks exactly how the image below looks. If it does, this test passes and the task is complete. 

![fuhdf.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/c1699a3b-ab6e-463a-b2a3-8c765654ef25)

**Comment by Nildham21** [comment]
Step 3, you can remove the following line "with the numbers removed from the description of the activity level. If it does, this test passes and the task is complete", since the user has no idea of what the pervious iteration looked like

**Comment by Nildham21** [comment]
Attach Survey page user story as dependency

**Comment by Nildham21** [comment]
Need to attach Attach Survey page user story as dependency still
