### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#15]
**Task Tests:** 

_Test 1_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Verify that the text "nutr.io" is displayed in big bold text at the top left side of the screen
3. Verify that the text "nutrition made easy" is displayed in smaller text below the text "nutr.io" on the left side of the screen
4. Verify an image of a carrot is displayed below the text "nutrition made easy" on the left side of the screen

_Test 2_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Verify that a form titled "login" is displayed on the right side of the screen
3. Verify that a text input box with the text "username" inside it is displayed in the form
4. Verify that a text input box with the text "password" inside it is displayed in the form
5. Verify that the text "already have an account? signup" is displayed at the bottom of the form
6. Click the blue linked text "signup" in the text "already have an account? signup" and verify the you have been redirected to the [Signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)

_Test 3_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Enter a username that you have not used to create an account on the signup page with in the username field in the login form
3. Enter any text in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. **This is used to test inputting an unregistered username with an incorrect password for a non-existent account**, verify that a pop up error message with the text "Please Enter Valid Username and Password" is displayed under the login form and the page is not redirected

_Test 4_

1. Go to the [Signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/) and create an account. You should be redirected to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Enter the username of the account you created in the username field in the login form
3. Enter the password of the account you created in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. **This is used to test inputting the correct username with the correct password for an existing account for the first time**, Verify that you have been redirected to the [Survey page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/survey/) 

_Test 5_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) 
2. Enter the username of the account you created in  _Test 4_  in the username field in the login form
3. Enter the password of the account you created in  _Test 4_  in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. **This is used to test inputting the correct username with the correct password for an existing account that is NOT the first login**, Verify that you have been redirected to the [Content page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/content/) 

_Test 6_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Enter "wrong" (or anything other than the the username you created in  _Test 4_) in the username field in the login form
3. Enter the password you created in  _Test 4_  in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. **This is used to test inputting the wrong username with the correct password for an existing account**, verify that a pop up error message with the text "Please Enter Valid Username and Password" is displayed at the top of the screen and the page is not redirected

_Test 7_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Enter the username you created in  _Test 4_ in the username field in the login form
3.Enter "wrong" (or anything other than the the password you created in  _Test 4_) in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. **This is used to test inputting a registered username with an incorrect password for an existing account**, verify that a pop up error message with the text "Please Enter Valid Username and Password" is displayed at the top of the screen and the page is not redirected

_Test 8_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Enter "wrong" (or anything other than the the username you created in  _Test 4_) in the username field in the login form
3. Enter "wrong" (or anything other than the the password you created in  _Test 4_) in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. **This is used to test inputting an unregistered username with an incorrect password**, verify that a pop up error message with the text "Please Enter Valid Username and Password" is displayed at the top of the screen and the page is not redirected

_Test 9_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Leave the username field in the login form blank
3. Leave the password field in the login form blank
4. Click the blue login button at the bottom of the login form
5. **This is used to test not inputting anything into the username and password fields**, Verify that you have not been redirected and the warning message with the text "Please fill out this field" is displayed under the username field in the login form

_Test 10_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Leave the username field in the login form blank
3. Enter the password you created from  _Test 4_  in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. **This is used to test not inputting anything into the username with the correct password**, Verify that you have not been redirected and the warning message with the text "Please fill out this field" is displayed under the username field in the login form

_Test 11_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Enter the username you created from  _Test 4_ in the username field in the login form
3. Leave the password field in the login form blank
4. Click the blue login button at the bottom of the login form
5. **This is used to test inputting a registered username while leaving the password field in the login form blank**, Verify that you have not been redirected and the warning message with the text "Please fill out this field" is displayed under the password field in the login form

**Comment by Nildham21** [comment]
This should have Task Tests instead of Acceptance Tests
