### ISSUE TITLE
As a person tracking their nutrition, I want to see my nutritional progress for the day on the main page when I login, so that I can easily track my macro/caloric goals as well as my meals

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#3]
**Acceptance Tests** 

__Test 1__
1) go to [login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2) login with the User `chad`
username is `chad`
password is `password`
3) press Enter
4) Verify that there is a progress circle on the left as well as the macro goals on the right. Below it should be a log of what the user ate
5) Verify the users username is displayed in the top right hand corner

__test 2__
1)go to the [login](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) page and use the credentials `username: j` `password: string` to login![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/d95f33f4-8512-4ffa-b7b6-bfd782dbcfe9) 
2)verify that each macro (protein carbs and fats) are 0/ 145 0/ 358.82 and 0/ 58 respectively and that in the circle the vale is 0/ 2537.28![cont.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/372085a0-3ec2-44d4-b379-c032b1210ad6) 

__test 3__
1)go to the [login](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) page and use the credentials `username: j` `password: string`![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/d5091fce-8d64-4be8-8856-e904a59ef2d2)
2)verify there are no meals added to meal history on the content page![cont.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/a1a9e5c3-4a35-4b97-aee1-59c9a8e0f595) 

__test 4__
1)go to the [login](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) page and use the credentials `username: j` `password: string` to login
2)click on `track page` on the top of the screen in the nav bar![track.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/f0642c48-c5e7-4df9-8709-0227cbfb6310)

3)Select todays date under date
4)Enter `121` under calories
5)Enter `9` under protein
6)Enter `8` under carbs
7)Enter `5` under fats
8)Submit by pressing `Enter` or `return`
9)Click the content page link in the top to direct back to the content page
10)Verify the meal was added to the food log with correct corresponding macros
11)Verify the calories says `121/2537.28` protein says: `9/145` grams carbs says: `8/358.82 `and fats says `5/58`

__test 5__
1)go to the [login](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) page and use the credentials `username: chad` `password: password` to login
2)click on `track page` on the top of the screen in the nav bar
3)Select todays date under date
4)Enter 200 for calories 
5)Enter 5 for protein
6)Enter 10 for carbs
7)Enter 15 for fats
8)Submit the form by pressing `Enter` or `return`
9)Click the content page on the top of the nav bar to direct back to the content page
10)Verify the meal was added to the food log with correct corresponding macros below the meal added previously
11)Verify the calories went up from `121` to `321` the protein went up from `9` to `14` the carbs went up from `8` to `18` and the fats went up from `5` to `20`

**Comment by Nildham21** [comment]
-The Figma test should be the first test the untrained users see so they are aware of what to expect when they do visit the content page URL.

-

**Comment by Nildham21** [comment]
Add sprint 4 label
