### ISSUE TITLE
Connect Login Form to DB

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#36]
**Task Tests**

_Test 1_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login)
2. Enter "wrong" in the username field in the login form
3. Enter "wrong" in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. Verify that a pop up error message with the text "Please Enter Valid Username and Password" is displayed under the login form and the page is not redirected

_Test 2_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login) 
2. Enter the username "timmy" which is one of our test users in the database in the username field in the login form
3. Enter the password of the account "password" in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. Verify that you have been redirected to the [Survey page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/survey) 

_Test 3_

1. Go to the [Login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login) 
2. Enter the username "chad" which is one of our test users in the database in the username field in the login form
3. Enter the password of the account "password" in the password field in the login form
4. Click the blue login button at the bottom of the login form
5. Verify that you have been redirected to the [Content page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/content) as "chad" has already logged in for the first time and took the survey already.

**Comment by Nildham21** [comment]
This is a task, so it should state Task Tests instead of Acceptance Tests
