### ISSUE TITLE
Connect Signup form to DB

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#37]
__Task Tests__

*Test 1*

1)go to [signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)
2)Enter an email without an @ sign.
3)Fill out the rest of the form with any username that is not blank
4)Input any two matching passwords in the next two field that are not blank
5)Submit and verify the form submission fails and asks for a valid email

*Test 2*

1)go to [signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)
2)Here are some valid inputs for testing purposes
Email: Email@example.com
Username: Username
Password: 123
Confirm Password: 123
leave any number of input fields blank with valid inputs in the rest of the fields
3)Submit the form and verify form submission fails with a prompt asking to fill out required fields

*Test 3*

1)go to [signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)
2)Enter valid inputs for Email and Username, example valid inputs are:
Email: Email@example.com
Username: Username
3)Enter two different passwords for password and confirm password
4)Submit the form and verify form submission fails with a prompt stating the passwords must match

*Test 4*

1)go to [signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)
2)Click the login link under the submit button that says "Already have an account? Login"
3)Verify the user is taken to the login page

*Test 5*

1)go to [signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)
2)Enter valid inputs for all fields.
Example valid inputs:
Email: Email@example.com
Username: Username
Password: 123
Confirm Password: 123
3)Submit the form and verify a green success message displays under the form

*Test 6*

1)go to [signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)
2)Enter valid inputs for all fields.
Example valid inputs:
Email: Email@example.com
Username: Username
Password: 123
Confirm Password: 123
3)Submit the form and click the "back to login" link on the success message
4)Verify this directs back to the login page

*Test 7*

1)go to [signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)
2) Enter chad@email.com in the email field
and
Username: Username
Password: 123
Confirm Password: 123
in remaining field
3)Submit and verify that error message states Email already taken

*Test 8*

1)go to [signup page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/signup/)
2) Enter Chad in the Username field
and
Email: example@example.com
Password: 123
Confirm Password: 123
in remaining field
3)Submit and verify that error message states Username already taken

**Comment by Nildham21** [comment]
For test 2, step 1 and 2 are on the same line. Please separate them.
