### ISSUE TITLE
As a person trying to live a healthier lifestyle, I want to be recommended exercises that burn a certain amount of calories, so that I stay within my daily calorie range.

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#4]
**Acceptance Tests**

_Test 1_
1. Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2. Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

3.  Once at the survey, enter the following values: 21 for the age, Male for the sex, 72 for the height and 185 for the weight, Lose Weight/Cut for the fitness goal, proteins for the macros, lactose and glucose intolerance for the dietary restrictions. and active for the activity level. After the values are entered, click the get started button and you should be redirected to the content page.
![cusa_content.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/1f724eb2-9c1e-4c9a-92f0-02910544b075)

4. Once on the content page, click the navbar link that reads "Exercise".

5. A list of 3 exercises, their difficulty and their descriptions should be displayed on the screen. The user's current fitness goal (which should be CUT if this was unchanged from the survey) should be displayed in the top left of the gray box holding the recommendations. A green "refresh" button should appear in the bottom right of the gray box holding the recommendations.  See the image below for an example of how the page should be laid out.

![ewgwegfewf.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/e2ab943a-9ad5-4256-ad9e-ab8abcc18821)

6. Remain logged into the same account you created and stay on the exercise page when moving to the next test, you will need to use these same credentials and this page later.

_Test 2_

1. If you are logged into the account created in Test 1, continue on to the next step. If not, repeat steps one through 4 of Test 1 and then navigate through this test. 

2. While on the exercise page, click the green refresh button in the bottom right of the recommendation box. 

![ewgwegfewf red.png](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/38d49f71-8352-4d77-a597-b849de7a2b81) 

3. This button should refresh the page which should present you with 3 new exercises. Some exercises may have been presented before the refresh, but as long as the exercises have changed this test passes. 

4. Remain logged into the same account you created and stay on the exercise page when moving to the next test, you will need to use these same credentials and this page later.

_Test 3_

1. If you are logged into the account created in Test 1, continue on to the next step. If not, repeat steps one through 4 of Test 1 and then navigate through this test. 

2. From the exercise page, click the navbar link that reads "Profile" to visit the profile page.

![rp.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/1c6bc211-7ded-4673-9011-da156af4c421)

3. Once here, click the blue edit profile button at the bottom which will allow the data to be edited. Once in edit mode, click the current goal drop down and change its value to "Maintain".  Click the blue save changes button once finished.

![sadfvads.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/187a026e-44df-4061-9242-a7b02c2a4b51)
![dsagedsg.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/1663ec2c-9153-40be-a70e-353911d13335)

4. Once step 3 is complete, click the navbar "Exercise" link to be redirected back to the exercise page. In the top left of the exercise recommendation box, "MAINTAIN" should be displayed as the current fitness goal and the exercises should be entirely different from the ones displayed when fitness was set to CUT. If it has not, this test fails. 

![efewagr.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/0607fc85-606c-43e1-b1b9-47dade1959ce)

**Comment by Nildham21** [comment]
Please add test of how this page is intended to be utilized
