### ISSUE TITLE
Create getCalorieGoals function

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#40]
**Task Tests**
_Test 1_
1) ssh into cheshire with `ssh {UBIT}@cheshire.cse.buffalo.edu`
2) Navigate to our project folder with `cd /web/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators`
3) Run `./phpunit tests/DBTest.php`
4) Verify all tests pass, below is an example of a successful test run. Note the `OK` in the last line
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/75c11c7b-bb90-4191-ad3c-ea73b720e488)
5) Verify no tests fail, below is an example of a failed test run. Note the `FAILURES!` on the second last line
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/97a0767c-eb39-4201-8676-7830af98050b)

**Comment by Nildham21** [comment]
Since the server code is not up to date, I currently cannot run to verify this.

Include a screenshot of the terminal so the untrained user can verify if they got the same result. Explain what each Failure or Success message means.
