### ISSUE TITLE
Create content page using HTML CSS and JS

### ISSUE THREAD

**Issue by JakeGuzzardo** [cse442-at-ub/project_s23-the-ai-violators#45]
![contentpageNutrio.jpg](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/e2b79bf3-1017-47f9-b1fd-627b9bda127e)

__Task Test__

*Test 1*
1) go to [login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/index.html)
2) login with the User `chad`
username is `chad`
password is `password`
3) press Enter
4) Verify that there is a progress circle on the left as well as the macro goals on the right. Below it should be a log of what the user ate
5) Verify the users username is displayed in the top right hand corner

*Test 2*
1) go to [login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/index.html)
2) click create account to create an account
3) go back to login by clicking `back to login` after the success message and login with that account
4) login and verify the content page has the Username in the top right hand corner

**Comment by Nildham21** [comment]
Update this as the page changes this week. 
Add a screenshot of what the content page looks like so an untrained user can verify that they are on the correct page.

**Comment by Nildham21** [comment]
Include an image of the content page to make sure the user is on the right page
