### ISSUE TITLE
Create Calorie Track Page

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#46]
**Acceptance Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "chad" and password "password" and verify you were redirected to the [Content Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/content/ )
3.  Click the link to the Track page and verify you are [there](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/track/ )
4. Verify there is a header with the an image of a carrot, text that says "nutr.io", a button to link back to the the content page, name of the user "chad" and a logout button
4. Check that a form is displayed to enter date, calories, carbs, protein, and fats into
3. Verify there is an add button

_Test 2_

1. Go to our [Track Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/track/ )
2. Don't enter anything into the form
3. Click the add button **This is used to test not inputting anything into the fields** Warning message with the text "Please fill out this field" is displayed under the date field

_Test 3_

1. Go to our [Track Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/track/ )
2. Enter "03/18/2023" into the date field
3. Enter "100" in the calorie field, "20" in the carbs field, "30" in the protein field, and "70" into fats
4. Click the add button
5. Verify a green success message pops up under the form that reads "Successfully Added"

_Test 4_

1. Go to our [Track Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/track/ )
2. Enter "03/18/2023" into the date field
3. Enter "100" in the calorie field, "20" in the carbs field, nothing in the protein field, and "70" into fats
3. Click the add button 
4. Verify a warning message with the text "Please fill out this field" is displayed under the protein field

**Comment by Nildham21** [comment]
Need to add more tests regarding valid inputs and missing inputs.

**Comment by Nildham21** [comment]
This should have Task tests not Acceptance Tests
