### ISSUE TITLE
Calorie Track Page in Figma

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#48]
**Acceptance Tests**

_Test 1_

1. Go to our [Figma Wireframe](https://www.figma.com/proto/fgwadQDkqlB8aiswfQUnV3/Free-Figma-Bootstrap-5-UI-Kit-(Community)?node-id=719%3A4&scaling=scale-down&page-id=718%3A3&starting-point-node-id=719%3A4 )
2. Click the login button
3. Verify you are now at the content page
4. Click the track button on the navigation bar at the top of the screen
5. Verify that you are at the Calorie Track page
6. Check that a form is displayed to enter: date, meal, calories, carbs, protein and fats into
7. Verify there is a blue button that says "Add"

**Comment by Nildham21** [comment]
Make this task a dependency of the Calorie Track User Story #6

**Comment by Nildham21** [comment]
This should have Task Tests instead of Acceptance Tests
