### ISSUE TITLE
As a person tracking their meals with nutr.io, I want to have access to a personalized profile page that allows me to edit user information and goals so that I can have my meal tracking match my real time goals.

### ISSUE THREAD

**Issue by adrienguan2** [cse442-at-ub/project_s23-the-ai-violators#50]
**Acceptance Tests**

_Test 1_
1. Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2. Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 
![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

3.  Once at the survey, enter the following values: 21 for the age, Male for the sex, 72 for the height and 185 for the weight, Lose Weight/Cut for the fitness goal, proteins for the macros, lactose and glucose intolerance for the dietary restrictions. and select the "active" a dropdown option in the activity level field. After the values are entered, click the get started button and you should be redirected to the content page.
![cusa_content.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/1f724eb2-9c1e-4c9a-92f0-02910544b075)

4. Once on the content page, click the navbar link that takes you to the profile page. 
![cusa_content.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/ee85bb03-e9a4-46f5-982d-9caae0763d14)

5. Ensure the statistics are displayed properly. Sex should display male, height should be formatted like a height should display the number 72, weight should display the number 185, current goal should be all caps and display LOSE WEIGHT/CUT. Focus macro should display PROTEIN in all caps. Calorie goal should display the calculated number (as long as this value is a number this is correct), activity level should display Active and finally restrictions should display Lactose Intolerance and Gluten Intolerance. 

NOTE: Stay on the profile page as you will need to be here for the next test.

_Test 2_ 
1. Assuming you are on the profile page, continue this test from here. If you are not on the profile page, navigate there using steps 1-4 of the previous test or just step 4 after logging in with your created credentials if you still have them. 
2. Click the edit profile button
![edit_prof.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/8539ad0d-276f-47e3-a5bd-b1249ff6a6d3)

3. Ensure all fields where user data is displayed except for email address can be changed in this state.  See step four for the guidelines
![edit.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/08d625d0-0eff-44cf-b053-63b03ab7f4a3)

4. Sex should present a dropdown box with the other 2 sex options. Height should present an input box that only allows 2  numbers and no letters. Weight should present an input box that only allows 3 numbers and no letters. Current goal and focus macros should both present dropdown boxes with the proper options within them. Activity Level should present dropdown boxes with various activity levels in within them. Restrictions should present check boxes that represent each of the restrictions in the list. 

5. Change any values (except for calorie goal) and click the Save Changes button. Your changes should be reflected on the profile page you were on before hitting edit profile.

NOTE: Stay on the profile page as you will need to be here for the next test.

_Test 3_
1. Assuming you are on the profile page, continue this test from here. If you are not on the profile page, navigate there using steps 1-4 of the previous test or just step 4 after logging in with your created credentials if you still have them. This test will ensure the layout of the page is displayed correctly.
2. Look in the top left corner of the page, ensure "Your Profile" and "Here's a look at you..." are displayed here.
3. Look below the elements in step 2, ensure the username is displayed above the profile image, a profile image or a placeholder for one is present, and the email address for the user is below the profile image. Check to see if the logout button is below this as well.
4. Look below the user profile picture and ensure all user statistics mentioned in Test 1 are in their own rows and the fonts are displayed in the nutr.io fonts in black and light gray. An image of a proper profile page can be seen below (activity level is missing in this image, it would be presented similarly to the other pieces of data and should be between restrictions and calorie goal.
![proper_profile.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/e121937f-e7f6-4194-aa11-93e930fa18cb)

5. Run through test 2 again after step 4 to completely ensure the page is being displayed properly. 

_Test 4_
1) Go to [our webapp](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Login with username: `Chad` and password: `password`
3) Click on profile in the navbar
4) Make a note of the current calorie goal
4) Click on edit profile
5) Change the weight to 250, then click save changes
6) Verify the calorie goal is different, make a note of this new goal
7) Click on edit profile
8) Change sex to female
9) Verify the calorie goal is different, make a note of this new goal
10) Click on edit profile
11) Change height to 60
12) Verify the calorie goal is different, make a note of this new goal
13) Click on edit profile
14) Change activity level to Professional Athlete
15) Verify the calorie goal is different

_Test 5_
1) Go to [our webapp](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators)
2) Login with username: `sib` and password: `password`
3) Click on `Profile` on the navbar
4) Click on the `Edit Profile` Button at the bottom of the page
5) Click `Browse` and select a non png, jpg, or jpeg file. It may be useful to create an empty txt file to use for this
6) Verify the error message says `An error occured. Only JPEG or PNG (not JPG) images under 5MB may be submitted`.

_Test 6_
1) Go to [our webapp](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators)
2) Login with username: `sib` and password: `password`
3) Click on `Profile` on the navbar
4) Click on the `Edit Profile` Button at the bottom of the page
5) Click `Browse` and select a png, or jpeg *NOT JPG* file under 5MB from your computer
6) After selecting a picture, click `Update Profile Picture`
7) Verify your new profile picture is now displayed

_Test 7_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "Profile Page" on the header bar.
4. Verify the text "cam@test.com" is displayed underneath the profile image

_Test 8_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "chad" and password "password" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "Profile Page" on the header bar.
4. Verify the text "chad@email.com" is displayed underneath the profile image.

**Comment by Nildham21** [comment]
This is a user story, switch the label to user story, and rename the 'Task Tests' to 'Acceptance tests'. Also this belongs in in progress since we still have more work to do with this story

**Comment by Nildham21** [comment]
Link the profile page in steps where you direct the user to go to the profile page

**Comment by Nildham21** [comment]
Include images of login page, content page and profile page

Since you are telling the user to log into an account, you know what the values of the profile page, please state them so the user can verify with them

**Comment by Nildham21** [comment]
Add print 4 label
