### ISSUE TITLE
As a returning user, I want to be presented the login page when I go to any page while logged out, so I can log back in

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#51]
**Acceptance Tests**

_Test 1_
1) Go to our [Web App](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/ )
2) Verify the login page is displayed
3) Change the url to ` .../project_s23-the-ai-violators/public/content`
4) Verify the login page is still displayed
5) Change the url to ` .../project_s23-the-ai-violators/public/track`
6) Verify the login page is still displayed
7) Login with username: `chad` and password: `password`
8) Verify the content page displays
9) Change the url to ` .../project_s23-the-ai-violators/public/track`
10) Verify the track page now displays
11) Change the url to ` .../project_s23-the-ai-violators/public/content`
12) Verify the content page now displays

**Comment by Nildham21** [comment]
Even though this is not implemented, you need to add tests of what the expected behavior is
