### ISSUE TITLE
Create Profile Page

### ISSUE THREAD

**Issue by adrienguan2** [cse442-at-ub/project_s23-the-ai-violators#54]
**Task Tests**

_Test 1_
1. Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2. Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

3.  Once at the survey, enter the following values: 21 for the age, Male for the sex, 72 for the height and 185 for the weight, Lose Weight/Cut for the fitness goal, any valid value for the calorie goal (this will be calculated unless a setting is changed otherwise), proteins for the macros, lactose and glucose intolerance for the dietary restrictions. and 4 for the activity level. After the values are entered, click the get started button and you should be redirected to the content page.
![cusa_content.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/1f724eb2-9c1e-4c9a-92f0-02910544b075)

4. Once on the content page, click the navbar link that takes you to the profile page. 
![cusa_content.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/ee85bb03-e9a4-46f5-982d-9caae0763d14)

5. Ensure the statistics are displayed properly. Sex should display male, height should be formatted like a height should display the number 72, weight should display the number 185, current goal should be all caps and display LOSE WEIGHT/CUT. Focus macro should display PROTEIN in all caps. Calorie goal should display the previously mentioned calculated number (as long as this value is a number this is correct), activity level should display 4 and finally restrictions should display Lactose Intolerance and Gluten Intolerance. 

NOTE: Stay on the profile page as you will need to be here for the next test.

_Test 2_ 
1. Assuming you are on the profile page, continue this test from here. If you are not on the profile page, navigate there using steps 1-4 of the previous test or just step 4 after logging in with your created credentials if you still have them. 
2. Click the edit profile button
![edit_prof.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/8539ad0d-276f-47e3-a5bd-b1249ff6a6d3)

3. Ensure all fields where user data is displayed except for email address can be changed in this state.  See step four for the guidelines
![edit.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/08d625d0-0eff-44cf-b053-63b03ab7f4a3)

4. Sex should present a dropdown box with the other 2 sex options. Height should present an input box that only allows 2  numbers and no letters. Weight should present an input box that only allows 3 numbers and no letters. Current goal and focus macros should both present dropdown boxes with the proper options within them. Calorie goal should present an input box that only allows 5 numbers and no letters. Restrictions should present check boxes that represent each of the restrictions in the list. 

5. Change any values (except for calorie goal) and click the Save Changes button. Your changes should be reflected on the profile page you were on before hitting edit profile.

NOTE: Stay on the profile page as you will need to be here for the next test.

_Test 3_
1. Assuming you are on the profile page, continue this test from here. If you are not on the profile page, navigate there using steps 1-4 of the previous test or just step 4 after logging in with your created credentials if you still have them. This test will ensure the layout of the page is displayed correctly.
2. Look in the top left corner of the page, ensure "Your Profile" and "Here's a look at you..." are displayed here.
3. Look below the elements in step 2, ensure the username is displayed above the profile image, a profile image or a placeholder for one is present, and the email address for the user is below the profile image. Check to see if the logout button is below this as well.
4. Look below the user profile picture and ensure all user statistics mentioned in Test 1 are in their own rows and the fonts are displayed in the nutr.io fonts in black and light gray. An image of a proper profile page can be seen below.
![proper_profile.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/e121937f-e7f6-4194-aa11-93e930fa18cb)

5. Run through test 2 again after step 4 to completely ensure the page is being displayed properly.

**Comment by Nildham21** [comment]
Can you link the profile page in steps where you direct them to visit it

**Comment by Nildham21** [comment]
Directing the user via link is no longer valid, users have to be signed in to view that page now. Can you please update your tests such that it requires the user to first log in and then access the profile page.

To make your tests better, I would suggest providing the untrained user an account they can log into, this way when they visit the profile page, instead of describing what should be there and in what format it should be, you can describe exactly what they should be viewing and how they can modify these values by using the edit button on the profile page.

**Comment by Nildham21** [comment]
All the tests from #50 should belong here
