### ISSUE TITLE
Update header on Track Page

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#56]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/a615394a-45bd-4bd4-9382-9aa0fd86bf0a)
4. Verify there is a header at the top of page displaying the following:
- Image of a carrot in the upper left corner with the text "nutr.io" to the right
- A link with the text "Content Page"
- A link with the text "Profile Page"
- A link with the text "History Page"
- A link with the text "Track Page"
- A link with the text "Recommendation Page"
- Text displaying the current user's username : "cam" in the upper right corner
- A link with the text "Logout"

**Comment by Nildham21** [comment]
Can you please include screenshots of each page that you direct the user to.

Need to update test1, step 3 since the nav bar is different now

Need to add tests for the new pages that have been added to the nav bar
