### ISSUE TITLE
Update History Page in Figma

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#57]
**Task Tests**

_Test 1_
1. Go to our [Figma Wireframe](https://www.figma.com/file/fgwadQDkqlB8aiswfQUnV3/Free-Figma-Bootstrap-5-UI-Kit-(Community)?node-id=718-3&t=QpatoxbHeZT2aejT-0) and navigate to the history page 
2. Verify you can see a table with the dates, meal name, calories, carbs, protein, and fats
3. Verify you can see edit and delete text for each row as well:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b9e17585-5fdc-4656-a7e3-2c3d5a228d58)

**Comment by Nildham21** [comment]
Please add task tests

**Comment by Nildham21** [comment]
Need to update these tests since the UI was changed

**Comment by Nildham21** [comment]
can you include an image of the history page wireframe
