### ISSUE TITLE
As a person tracking their nutrition intake, I want to be able to input what calories and macros I consumed, so my daily intake can be recorded.

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#6]
**Acceptance Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/321eeadb-aba6-486c-9635-6858cc8da945)
4. Verify there is a header with the an image of a carrot, text that says "nutr.io", "Content Page", "Profile Page", "History Page", "Track Page", "Recommendation Page", "cam", "logout"
4. Check that a form is displayed to enter date, meal name, calories, carbs, protein, and fats into
3. Verify there is an add button

_Test 2_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/4be10e4e-bb14-4d2d-86a5-8db1b7c64298)
4. Enter today's date into the Date field
5. Enter "steak" into the Meal field
6. Enter "400" into the Calories field
7. Enter "10" into the Carbs field
8. Enter "20" into the Protein field
9. Enter "30" into the Fats field
10. Click the blue "Add" button at the bottom of the screen
11. Verify that a green popup message with the text "Successfully Added" is displayed at the bottom of the screen 
12. Click the text "Content Page" on the header bar and make sure you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/77e1828d-fa2a-43e9-b9f4-1700e3ad0190)
13. Find the Meal History table at the bottom of the page and verify there is a row in the table with the values [steak, 400, 10, 20, 30]

_Test 3_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/4be10e4e-bb14-4d2d-86a5-8db1b7c64298)
4. Enter today's date into the Date field
5. Leave the Meal field blank
6. Enter "400" into the Calories field
7. Enter "10" into the Carbs field
8. Enter "20" into the Protein field
9. Enter "30" into the Fats field
10. Click the blue "Add" button at the bottom of the screen
11. Verify that a popup message with the text "Please fill out this field" is displayed under the Meal field

_Test 4_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/4be10e4e-bb14-4d2d-86a5-8db1b7c64298)
4. Don't enter anything into the form
5. Click the add button and verify that a popup message with the text "Please fill out this field" is displayed under the date field

**Comment by Nildham21** [comment]
Need to add more tests regarding valid inputs and missing inputs.

Once a user enters the calories and macros how can they verify it was successfully added and stored? Direct them back to the content page so they can view the change on the tracker wheel.

**Comment by Nildham21** [comment]
This should have Task Tests instead of Acceptance Tests

**Comment by Nildham21** [comment]
The test steps need to be more detailed, like the sign up and log in page, provide the user sample numbers they can input and what they expected output should be when they press add

**Comment by Nildham21** [comment]
Need to update these tests, since an additional input value was added.
