### ISSUE TITLE
Add meal name to DB

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#60]
**Task Tests**

_Test 1_
1) Got to [phpAdmin](https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/)
2) Log in with USERNAME: `sjrichel` PASSWORD `50338787`
3) In the left bar, click on `cse442_2023_spring_team_g_db`
4) Click on the `daily_intake` table
5) Verify one of the columns is `meal_name`

**Comment by Nildham21** [comment]
You can add this task to the tracking meal user story
