### ISSUE TITLE
Add restrictions to DB

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#61]
**Task Tests**

_Test 1_
1) Got to [phpAdmin](https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/)
2) Log in with USERNAME: `sjrichel` PASSWORD `50338787`
3) In the left bar, click on `cse442_2023_spring_team_g_db`
4) Click on the `restrictions` table
5) Verify there are restrictions with ids in the table

**Comment by Nildham21** [comment]
The wrong user story is attached to this user story, you should add this task as part of the survey page user story
