### ISSUE TITLE
Fix the CSS of the profile page

### ISSUE THREAD

**Issue by adrienguan2** [cse442-at-ub/project_s23-the-ai-violators#63]
**Task Tests**

_Test 1_
1. Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2. Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

3.  Once at the survey, enter the following values: 21 for the age, Male for the sex, 72 for the height and 185 for the weight, Lose Weight/Cut for the fitness goal, any valid value for the calorie goal (this will be calculated unless a setting is changed otherwise), proteins for the macros, lactose and glucose intolerance for the dietary restrictions. and 4 for the activity level. After the values are entered, click the get started button and you should be redirected to the content page.
![cusa_content.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/1f724eb2-9c1e-4c9a-92f0-02910544b075)

4. Once on the content page, click the navbar link that takes you to the profile page. 
![cusa_content.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/ee85bb03-e9a4-46f5-982d-9caae0763d14)

5. Once on the profile page, you will need to do some resizing to ensure the elements on the page display properly regardless of the page size. Pop out your browser window and make its width as small as your browser will allow. In google chrome on windows 10 you can resize a window to be like the image below. On your machine, try to emulate this to mimic what the page would look like on a mobile device. 

![resize.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/5665e8d1-df29-49bd-bab5-c2bb273b1a2e)

Make sure no words are being clipped off the screen and all user statistics are being displayed properly and are readable even after scrolling. If you are unsure how things should look, take a look at issue #50 on the scrum board which highlights how profile statistics should be displayed in its first test. The image above shows a good example of how things should look as well. 

6. Now resize the page to be half of its maximized size, take a look at the image below for an example. 
![halfresizie.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b10054d8-359d-46d7-b30d-152002416f75)

Make sure no words are being clipped off the screen and all user statistics are being displayed properly and are readable. If you are unsure how things should look, take a look at issue #50 on the scrum board which highlights how profile statistics should be displayed in its first test. The image above shows a good example of how things should look as well.  After checking the resizing from this step and step 5, if everything looks okay then it can be assumed the page will display correctly regardless of resizing, and this test passes.

**Comment by Nildham21** [comment]
Since this task was used to fix the page for resizing, the tests should reflect that, so you can just have one test, that requires the user to log in or sign up, go to the profile page and ask the user to resize the window in different sizes to ensure that the page stays in tact and no element leaks or overflows into another
