### ISSUE TITLE
Convert UTC to EST on server side

### ISSUE THREAD

**Issue by JakeGuzzardo** [cse442-at-ub/project_s23-the-ai-violators#64]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/83a7517c-95d0-41d6-9770-747e83a4196b)

2. Login in with test username `j` and password `string` and verify you were redirected to the content page ![cont.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/7e83bf5c-4a03-4ed3-9e43-212d7cf6a9bd)

3.  Click the link to the Track page on the top of screen in the nav bar and verify you are directed to the following page![track.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/a99ba915-bcf4-4d1e-a6e0-0728a8af0d06) 
4. add a meal and set the date to todays date
5. put Test for food name, 100 for calories 4 for protein 5 for carbs and 6 for fats
6. add the meal by clicking the add button or pressing enter
7. click `content page` to go back to the content page and verify the meal shows on the content page. Here is an example![contfill.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/2528d6bc-ed6f-43da-a5fc-586860d5fb2c) 

_Test 2_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/83a7517c-95d0-41d6-9770-747e83a4196b)

2. Login in with test username `j` and password `string` and verify you were redirected to the content page ![cont.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/7e83bf5c-4a03-4ed3-9e43-212d7cf6a9bd)

3.  Click the link to the Track page on the top of screen in the nav bar and verify you are directed to the following page![track.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/a99ba915-bcf4-4d1e-a6e0-0728a8af0d06) 
4. add a meal and set the date to yesterdays date
5. put Test2 for food name, 200 for calories and 4 for protein 5 for carbs and 6 for fats
6. add the meal by clicking add or pressing Enter
7. click the content page link in the nav bar and verify the meal is not shown on the content page

_Test 3_
1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/83a7517c-95d0-41d6-9770-747e83a4196b)

2. Login in with test username `j` and password `string` and verify you were redirected to the content page ![cont.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/7e83bf5c-4a03-4ed3-9e43-212d7cf6a9bd)

3.  Click the link to the Track page on the top of screen in the nav bar and verify you are directed to the following page![track.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/a99ba915-bcf4-4d1e-a6e0-0728a8af0d06) 
4. add a meal and set the date to tomorrows date
5. put Test3 for food name, 300 for calories and 5 for protein 6 for carbs and 7 for fats
6. add the meal by clicking add or pressing Enter
7. click the content page link in the nav bar and verify the meal is not shown on the content page

**Comment by Nildham21** [comment]
Test 2 is written twice, please remove it once

Instead of having directions such as "verify you were redirected to the Content Page", and providing a link, can you please attach a screenshot of what the content page looks like so they can verify they are on the right page?

The same applies to the track page.

Step 7, how do they go back to the content page? What should they click to return to the content page? Please be more clear.

Step 7, since you gave the user a specific value to enter for the meal name when they verify they should be checking for this value in the meal name section. Be specific in what the meal name should be when they check
