### ISSUE TITLE
Add meal name input to Track Page

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#67]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/4be10e4e-bb14-4d2d-86a5-8db1b7c64298)
4. Verify there is an input that is labeled "Meal" with an input box with the text "name" in it, that is a the top right of the screen next to the date input

_Test 2_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/4be10e4e-bb14-4d2d-86a5-8db1b7c64298)
4. Enter today's date into the Date field
5. Enter "steak" into the Meal field
6. Enter "400" into the Calories field
7. Enter "10" into the Carbs field
8. Enter "20" into the Protein field
9. Enter "30" into the Fats field
10. Click the blue "Add" button at the bottom of the screen
11. Verify that a green popup message with the text "Successfully Added" is displayed at the bottom of the screen 
12. Click the text "Content Page" on the header bar and make sure you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/77e1828d-fa2a-43e9-b9f4-1700e3ad0190)
13. Find the Meal History table at the bottom of the page and verify there is a row in the table with the values [steak, 400, 10, 20, 30]

_Test 3_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/4be10e4e-bb14-4d2d-86a5-8db1b7c64298)
4. Enter today's date into the Date field
5. Leave the Meal field blank
6. Enter "400" into the Calories field
7. Enter "10" into the Carbs field
8. Enter "20" into the Protein field
9. Enter "30" into the Fats field
10. Click the blue "Add" button at the bottom of the screen
11. Verify that a popup message with the text "Please fill out this field" is displayed under the Meal field

**Comment by Nildham21** [comment]
For each page that you direct the user to can you include a screenshot of what the page looks like so an untrained user can verify if they are on the right page.

Test 1 (2 and 3), Step 3, what link? Where is this link located?
