### ISSUE TITLE
Update survey page to store restrictions in database

### ISSUE THREAD

**Issue by adrienguan2** [cse442-at-ub/project_s23-the-ai-violators#68]
**Task Tests**

_Test 1_
1.) Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2.) Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

3.) Fill out the survey with proper values for all fields except the restrictions field. Here only check Lactose Intolerance and Gluten Intolerance. After this is done submit the survey and you should be directed to the content page.
4.) Click the link in the navbar to be directed to the profile page. Look at the user statistics and verify the only restrictions displayed are Lactose Intolerance and Gluten Intolerance.
![content_jack.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/cce14849-0bba-4442-9b18-383f220b5959)

![restrictions_work.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/88089218-1221-4e76-94ca-99470f1eeb96)

**Comment by Nildham21** [comment]
Add the user story related to this task as the dependency

**Comment by Nildham21** [comment]
Include screenshots of the page the user should be redirect to

Provide link for the login page
