### ISSUE TITLE
create meal recommendation page

### ISSUE THREAD

**Issue by JakeGuzzardo** [cse442-at-ub/project_s23-the-ai-violators#70]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/95f648e3-538e-4aaa-8326-593413b30501) 

2. Login in with test username "chad" and password "password" and verify you were redirected to the [Content Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/content/ )

3. Select the recommendations tab in the navbar on the top of the screen![rec.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/dfc218e5-76d0-4755-835c-49d5c337621b)

4. Verify that you are brought to a meal recommendation page that recommends 3 meals based on calories and an add button next to each meal.

_Test 2_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "chad" and password "password" and verify you were redirected to the [Content Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/content/ )
3. Select the recommendations tab in the navbar on the top of the screen
4. Verify that you are brought to a meal recommendation page
5. Click on any of the other navbar links and verify you are brought to the respected page

**Comment by Nildham21** [comment]
Please add task tests

**Comment by Nildham21** [comment]
You accidentally wrote Task Tests twice, remove the second occurrence of this

**Comment by Nildham21** [comment]
What is the purpose of test 2?

**Comment by Nildham21** [comment]
Include screen shots of each page that you direct the user to

**Comment by Nildham21** [comment]
You mention the refresh button, add a test to describe its functionality
