### ISSUE TITLE
Connect back end functions to meal recommendation page

### ISSUE THREAD

**Issue by JakeGuzzardo** [cse442-at-ub/project_s23-the-ai-violators#72]
**Task Tests**

_Test 1_
1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/83a7517c-95d0-41d6-9770-747e83a4196b)

2. Login in with test username `j` and password `string` and verify you were redirected to the![contentpage.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/c9b67777-89ce-4fe5-8d57-319c6070ce8d)
3. Click on Recommendation Page in the top right and verify you are redirected to the following page ![rec.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/040bd879-a2ec-46a0-85ad-96b27c50df93)

_Test 2_
1. repeat test 1 
2. Click add on any of the 3 food options
3. verify that you are prompted that the food has been added![recadded.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/8b0cbebd-88e8-474a-bac0-bd61c34d200a)

_Test 3_
1. Complete test 2 at least 1 time
2. Click on the `history page`  link in the nav bar and verify you are directed to the following page ![mealhist.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/20177aa2-fc44-4bd9-b0a2-78e5fd51ad96)
3. Verify that your recently added meal or meals now appears in the meal history page

_Test 4_
1. Complete test 2 at least 1 time
2. Click on the `content page` link in the nav bar
3. verify that your recently added meal or meals now appear in the meal history section on the content page (this represents the meal history for just the current day)![mealhistcont.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/eab82646-300c-41ac-b45d-fa3246ed4a2f)

**Comment by Nildham21** [comment]
Please add task tests
