### ISSUE TITLE
As a user that is logged into the web application, I want a logout button on the nav bar, so I can exit out of my account

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#75]
**Acceptance Tests**

_Test 1_
1) Go to the [Our web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Login with Username: `chad` and Password: `password` 
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/2dbfbae8-05ce-46f2-905a-d7a956f026a0)
3) Click `logout` in the top right
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/fe7553dc-6927-41dc-b34f-076b1506bd1a)
4) Verify you are brought back to the login page
5) Click the left arrow in your browser to go back to the previous page
6) Verify you are still on the login page

_Test 2_
1) Go to the [Our web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Login with Username: `chad` and Password: `password` 
3) Click `profile page` in the navbar
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/697181f5-0a1f-40be-840c-76870d073b55)
4) Click `logout` in the top right
5) Verify you are brought back to the login page
6) Click the left arrow in your browser to go back to the previous page
7) Verify you are still on the login page

_Test 3_
1) Go to the [Our web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Login with Username: `chad` and Password: `password` 
3) Click `history page` in the navbar
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/5d8d672d-8345-4b3a-be38-500878f78875)
4) Click `logout` in the top right
5) Verify you are brought back to the login page
6) Click the left arrow in your browser to go back to the previous page
7) Verify you are still on the login page

_Test 4_
1) Go to the [Our web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Login with Username: `chad` and Password: `password` 
3) Click `track page` in the navbar
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/e57ad1f0-fd38-4e7c-81b4-cbb645ff2f95)
4) Click `logout` in the top right
5) Verify you are brought back to the login page
6) Click the left arrow in your browser to go back to the previous page
7) Verify you are still on the login page

_Test 5_
1) Go to the [Our web app](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Login with Username: `chad` and Password: `password` 
3) Click `recomendation page` in the navbar
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/a8963d10-4424-4736-a934-aff2b428ea96)
4) Click `logout` in the top right
5) Verify you are brought back to the login page
6) Click the left arrow in your browser to go back to the previous page
7) Verify you are still on the login page

**Comment by Nildham21** [comment]
Can you please include screenshots of the content page, and all the other pages that the user is directed to throughout the tests

**Comment by Nildham21** [comment]
This should be a user story, for instance "As a user that is logged into the web application, I want a logout button on the nav bar, so I can exit out of my account"

**Comment by Nildham21** [comment]
Add task #74 as a dependency
