### ISSUE TITLE
Create and populate excersises DB table

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#76]
**Task Tests**

_Test 1_
1) Got to [phpAdmin](https://www-student.cse.buffalo.edu/tools/db/phpmyadmin/)
2) Log in with USERNAME: `sjrichel` PASSWORD `50338787`
3) In the left bar, click on `cse442_2023_spring_team_g_db`
4) Click on the `exercises` table
5) Verify there are exercises with ids in the table

**Comment by Nildham21** [comment]
please add test tasks

**Comment by Nildham21** [comment]
Attach this task as a dependency of the exercise recommendations page
