### ISSUE TITLE
Create a wireframe of the exercise recommendation page.

### ISSUE THREAD

**Issue by adrienguan2** [cse442-at-ub/project_s23-the-ai-violators#77]
**Task Tests**

_Test 1_

1. Go to our [Figma Workspace.](https://www.figma.com/file/fgwadQDkqlB8aiswfQUnV3/Free-Figma-Bootstrap-5-UI-Kit-(Community)?node-id=993-37&t=EqWMtlMhJVv6xP6J-0)
2. Look over the section of the workspace named "Exercise Page".
3. Ensure all necessary elements are there and the Exercise recommendation page looks presentable. There should be 10 exercises presented, with titles for each, and below the titles there should be a short description of what the exercise focuses on and the sets that should be conducted. The exercises should be in white boxes encased by a large gray rectangle, and a title attached to this rectangle should read "Exercise Recommendations - Current Fitness Goal: Lose Weight/ CUT This is a simple test that passes only through user interpretation, if this page looks different than desired this test should fail. See the image below for what the page should look like when clicking the link. 
![rec.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/d6c9879b-cc1d-4865-afdd-9d2d64e13883)

**Comment by Nildham21** [comment]
How does the user know what the "necessary elements" are? You need to state them so the user is aware what they are checking for
