### ISSUE TITLE
As a person tracking their meals, I want to go to the history page, so that I can see a calorie and macro history of previous days.

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#8]
**Acceptance Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "Track Page" on the header bar and verify you are there:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b530e380-3f59-431d-a7f8-13929f89a693)
4. Enter today's date into the Date field
5. Enter "steak" into the Meal field
6. Enter "400" into the Calories field
7. Enter "10" into the Carbs field
8. Enter "20" into the Protein field
9. Enter "30" into the Fats field
10. Click the blue "Add" button at the bottom of the screen
11. Click the text "History Page" on the header bar and verify there is row in the table with all the information you entered on the track page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/0f4247cc-bf9e-4659-82b1-a91d8970d627)

_Test 2_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "History Page" on the header bar and verify there is row in the table with all the information you entered on the track page in _Test 1_: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/0f4247cc-bf9e-4659-82b1-a91d8970d627)
4. Click the "Edit" button in the row and verify text in the row turns into inputs:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/83156acb-5bfd-4c7d-9faf-bd0eab929cd6)
5. Change the date from "today date" to "2023-04-14"
6. Change Meal from "steak" to "corn"
7. Change Calories from "400" to "80"
8. Change Protein from "10" to "60"
9. Change Carbs from "20" to "50"
10. Change Fats from "30" to "40"
11. Click the "Save" button in the row and verify the row was updated:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d62de604-d781-40ed-9e3a-06ccfccf549f)

_Test 3_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "History Page" on the header bar and verify there is row in the table with all the information you edited in _Test 2_: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d62de604-d781-40ed-9e3a-06ccfccf549f)
4. Click the "Delete" button in the row and verify the table is empty: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/25e3eddf-a487-4659-82aa-768a512ad66d)

_Test 4_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "Track Page" on the header bar and verify you are there:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b530e380-3f59-431d-a7f8-13929f89a693)
4. Enter 04/30/2023 into the Date field
5. Enter "steak" into the Meal field
6. Enter "400" into the Calories field
7. Enter "10" into the Carbs field
8. Enter "20" into the Protein field
9. Enter "30" into the Fats field
10. Click the blue "Add" button at the bottom of the screen
11. Enter 05/01/2023 into the Date field
12. Enter "corn" into the Meal field
13. Enter "320" into the Calories field
14. Enter "80" into the Carbs field
15. Enter "90" into the Protein field
16. Enter "50" into the Fats field
17. Click the blue "Add" button at the bottom of the screen
18. Click the text "History Page" on the header bar, click the "All History" button at the top of the page and verify there is row in the table with all the information you entered on the track page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b1cdac16-f428-43d7-a1bd-472047133d36)

_Test 5_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "History Page" on the header bar and verify there is row in the table with all the information you entered on the track page in Test 1: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b1cdac16-f428-43d7-a1bd-472047133d36)
4. Enter 04/30/2023 into the Date field
5. Verify the table is updated to show 1 element in the table with the information you entered for 04/30/2023 on the track page in Test 1: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/37e1af7a-d835-4343-b046-63a217d5bcc8)
6. Click the "All History" button at the top of the page and verify there is row in the table with all the information you entered on the track page in test 1: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b1cdac16-f428-43d7-a1bd-472047133d36)

_Test 6_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "History Page" on the header bar and click the "All History" button at the top of the page and verify there is row in the table with all the information you entered on the track page in test 1: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b1cdac16-f428-43d7-a1bd-472047133d36)
4. Enter 05/01/2023 into the Date field
5. Verify the table is updated to show 1 element in the table with the information you entered for 05/01/2023 on the track page in Test 1: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b18bc795-c6e6-477f-a97c-ac03806761e7)
6. Click the "All History" button at the top of the page and verify there is row in the table with all the information you entered on the track page in test 1: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b1cdac16-f428-43d7-a1bd-472047133d36)

_Test 7_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "History Page" on the header bar and click the "All History" button at the top of the page and verify there is row in the table with all the information you entered on the track page in test 1: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b1cdac16-f428-43d7-a1bd-472047133d36)
4. Enter 05/02/2023 into the Date field
5. Verify the table is updated to show no elements in the table: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/8b7a564f-06d9-4ae7-b741-f99ae9948e1b)
6. Click the "All History" button at the top of the page and verify there is row in the table with all the information you entered on the track page in test 1: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b1cdac16-f428-43d7-a1bd-472047133d36)

**Comment by Nildham21** [comment]
Please add task tests

**Comment by Nildham21** [comment]
You can not direct the user straight to the history page, must log in and follow other steps. Include screenshots when user is redirected to a new page

Need more tests
- A test to verify a new row is added into the history page
- A test to for the edit button
- A test for the delete button
