### ISSUE TITLE
Update Login page for mobile

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#81]
_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Change the size of the window by moving it to the smallest horizontal size
3. Verify it looks like this: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/7432e60e-18ab-49fc-9029-85a9f01a3fac)

**Comment by Nildham21** [comment]
missing a dependency, this should be blocking the track page user story
