### ISSUE TITLE
Update Track Page for mobile

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#82]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "cam" and password "camtest" and verify you were redirected to the Content Page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/5bbf9a10-d6ad-4c8f-b8b6-ca59f7502806)
3.  Click the text "Track Page" on the header bar and verify you are there: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/a615394a-45bd-4bd4-9382-9aa0fd86bf0a)
4. Change the size of the window by moving it to the smallest horizontal size
5. Verify it looks like this: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/1ca3f587-0f47-4a54-af03-30a8b028452b)

**Comment by Nildham21** [comment]
missing a dependency, this should be blocking the track page user story
