### ISSUE TITLE
Handle food recommendations when the user has too few calories left

### ISSUE THREAD

**Issue by JakeGuzzardo** [cse442-at-ub/project_s23-the-ai-violators#85]
__Task Tests__

*Test 1*
1) Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/83a7517c-95d0-41d6-9770-747e83a4196b)
2) Login in with test username `j` and password `string` and verify you were redirected to the content page
3) Click on the `Track` link in the navbar
4) Add a food of the name `Test`. Set the calories to `2100` Set date to `todays date`, and set the macro nutrients to numeric values of your choice.
5) Navigate to the meals page by clicking `meals` in the nav bar
6) Verify that instead of recommending foods, you are presented with the message "You do not have sufficient calories to be recommended anything at the moment"

*Test 2*
1) Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/83a7517c-95d0-41d6-9770-747e83a4196b)
2) Login in with test username `j` and password `string` and verify you were redirected to the content page
3) Click the History nav link in the nav bar and make sure to delete all entries
4) Click the Mealss tab in the nav bar and verify that 3 meals are being recommended

*Test 3*
1) Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/83a7517c-95d0-41d6-9770-747e83a4196b)
2) Login in with test username `j` and password `string` and verify you were redirected to the content page
3) Click the history page in the nav bar and make sure to delete all previous entries
4) Click on the `Track` link in the navbar
5) Enter a food named `Test` Set the date to `todays date`. Set the calories to `50` Set Protein to `200` carbs to `0` and fats to `0`
6) Submit the form
7) Navigate to the Meals page and verify that all recommended foods have at most 4 grams of protein

*Test 4*
1) Follow directions of Test 3 up to but not including step 5.
2) Enter a food named `Test` Set the date to `todays date`. Set the calories to `50` Set Protein to `0` carbs to `999` and fats to `0`
3) submit the form
4) Navigate to the Meals page and verify that all recommended foods have at most 4 grams of carbs

*Test 5*
1) Follow directions of Test 3 up to but not including step 5.
2) Enter a food named `Test` Set the date to `todays date`. Set the calories to `50` Set Protein to `0` carbs to `0` and fats to `120`
3) submit the form
4) Navigate to the Meals page and verify that all recommended foods have at most 4 grams of fats

*Test 6*
1) Follow directions of Test 3 up to but not including step 5.
2) Enter a food named `Test` Set the date to `todays date`. Set the calories to `50` Set Protein to `999` carbs to `999` and fats to `99`
3) submit the form
4) Navigate to the Meals page and verify that all recommended foods have at most 4 grams of fats 4 grams of protein and 4 grams of carbs.

**Comment by Nildham21** [comment]
Add task tests

**Comment by Nildham21** [comment]
Test 2, Step 3 states 'Click the History nav link in the nav bar and make sure to delete all entries' and Step 4 states 'Click on the Meal History Tab in the nav bar and delete the added Test Meal'. You are telling the user to delete all the entries before stating how to actually delete them. I would get rid of 'and make sure to delete all entries' in step 3. and after step 4 tell the user to make sure all the entires are deleted and if not delete so.

**Comment by Nildham21** [comment]
Test 3, step 7 fix style and indentation

**Comment by Nildham21** [comment]
Test 6 is written as Test 5

**Comment by Nildham21** [comment]
Attempted to login with username j and password string, and I receive the following message "Please Enter Valid Username and Password". Please provide different account credentials
