### ISSUE TITLE
Write getEmail function in PHP

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#86]
**Task Tests**
_Test 1_
1) ssh into cheshire with `ssh {UBIT}@cheshire.cse.buffalo.edu`
2) Navigate to our project folder with `cd /web/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators`
3) Run `./phpunit tests/DBTest.php`
4) Verify all tests pass, below is an example of a successful test run. Note the `OK` in the last line
![Screenshot 2023-04-23 at 7.33.56 PM.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/85c15af9-434f-43bf-97ea-41b13e034570)
5) Verify no tests fail, below is an example of a failed test run. Note the `FAILURES!` on the second last line
![Screenshot 2023-04-23 at 7.34.20 PM.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/2f6490ae-0820-4a7c-a18b-2995fd511376)

**Comment by Nildham21** [comment]
Need to add a task label, and attach the user story that this task is responsible for

**Comment by Nildham21** [comment]
Remove #87 from blocking dependency, and replace it with the Profile page user story
