### ISSUE TITLE
Have email of user display on Profile Page

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#87]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "Profile Page" on the header bar.
4. Verify the text "cam@test.com" is displayed underneath the profile image

_Test 2_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "chad" and password "password" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "Profile Page" on the header bar.
4. Verify the text "chad@email.com" is displayed underneath the profile image.

**Comment by Nildham21** [comment]
Need to attach the user story that this task is responsible for

**Comment by Nildham21** [comment]
Remove task #86 from the blocked by dependency
