### ISSUE TITLE
Fix editing height and weight on Profile Page

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#88]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "Profile Page" on the header bar and verify you are there:![Screenshot 2023-04-23 at 8.37.41 PM.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/eb4f3791-22db-4fda-88bc-9b78ceb5b4be)
4. Click the blue "Edit Profile" button at the bottom of the page
5. Enter Height as 60
6. Click the blue "Save Changes" button at the bottom of the screen
7. Verify the height is now displayed as 60:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/e684676a-7045-4576-b0cf-9407620aec78)

_Test 2_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/d6db61a3-615b-4049-b2d8-c7d0f9ef1add)
3. Click the text "Profile Page" on the header bar and verify you are there:![Screenshot 2023-04-23 at 8.37.41 PM.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/eb4f3791-22db-4fda-88bc-9b78ceb5b4be)
4. Click the blue "Edit Profile" button at the bottom of the page
5. Enter Weight as 182
6. Click the blue "Save Changes" button at the bottom of the screen
7. Verify the height is now displayed as 182:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/eeefdb8a-b085-4c76-b501-1801db064e56)

**Comment by Nildham21** [comment]
Need to attach the user story that this task is responsible for
