### ISSUE TITLE
Fix Protein Bug on Survey

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#89]
**Task Tests**

_Test 1_
1. Go to the [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/) and click signup.
![signup_highlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/df90c21c-e255-4bd3-9860-91e8b98fdd07)
2. Create a new account and write down the username and password. Click the link to the login page at the bottom of the signup sheet and enter these credentials. 

![login_redirhighlight.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/b3b1922f-df61-4730-91eb-a20dc9d25c61)
You should be presented with the initial survey after signing in for the first time.
![survey_redirect.PNG](https://images.zenhubusercontent.com/63e6a7b2f056a640e0f35fd7/eb5a2e00-1fe5-47c8-9c5b-d91d4b03485a)

4.  Select "Protein" for focus, and fill in the rest of the survey info with arbitrary values.
5.  Click "Get Started" and verify you are brought to the content page.
![image.png](https://images.zenhubusercontent.com/63e4030290130a7c1abd1b1f/054360f3-5ca2-4d2a-a250-aff17980a738)

**Comment by Nildham21** [comment]
Need to attach the user story that this task is responsible for

**Comment by Nildham21** [comment]
This is a task so the first line should be "Task Tests" not "Acceptance Tests"

**Comment by Nildham21** [comment]
For Step 5 can you provide a screenshot of what the content page looks like so the user can verify they are on the right page
