### ISSUE TITLE
As a person tracking their meals, I want to go to the recommendations page, so I find meals that meet my calorie/macro goals.

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#9]
**Acceptance Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )![log.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/95f648e3-538e-4aaa-8326-593413b30501) 

2. Login in with test username "chad" and password "password" and verify you were redirected to the [Content Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/content/ )

3. Select the meals tab in the navbar on the top of the screen![rec.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/dfc218e5-76d0-4755-835c-49d5c337621b)

4. Verify that you are brought to a meal recommendation page that recommends 3 meals based on calories and an add button next to each meal.

_Test 2_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username "chad" and password "password" and verify you were redirected to the [Content Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/content/ )
3. Select the meals tab in the navbar on the top of the screen
4. Verify that you are brought to a meal recommendation page
5. Click on any of the other navbar links and verify you are brought to the respected page

_Test 3_
1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/ )
2. Login in with test username `j` and password `string` and verify you were redirected to the![contentpage.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/c9b67777-89ce-4fe5-8d57-319c6070ce8d)
3. Click on meals Page in the top right and verify you are redirected to the following page ![rec.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/040bd879-a2ec-46a0-85ad-96b27c50df93)

_Test 4_
1. repeat test 1 
2. Click add on any of the 3 food options
3. verify that you are prompted that the food has been added![recadded.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/8b0cbebd-88e8-474a-bac0-bd61c34d200a)

_Test 5_
1. Complete test 2 at least 1 time
2. Click on the `history page`  link in the nav bar and verify you are directed to the following page ![mealhist.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/20177aa2-fc44-4bd9-b0a2-78e5fd51ad96)
3. Verify that your recently added meal or meals now appears in the meal history page

_Test 6_
1. Complete test 2 at least 1 time
2. Click on the `content page` link in the nav bar
3. verify that your recently added meal or meals now appear in the meal history section on the content page (this represents the meal history for just the current day)![mealhistcont.PNG](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/eab82646-300c-41ac-b45d-fa3246ed4a2f) 

_Test 7_
1) go to our [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Click on Sign up and create an account with the following info.
Email: TestUser2023@gmail.com
username: TestUser2023
password: string
confirm Password: string
3) Click the back to login prompt
4) Enter the following Credentials and click login
username: TestUser2023
password: string
5) At the one time survey page enter the following info:
Age: 21
Sex: Male
Height: 70
weight: 150
Select your goal: Maintain
Macro nutrient focus: Proteins
Activity Level: Moderately active
6) Press Get started
7) Verify that you are brought to the content page![homepage.png](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/a323b9cc-e8db-4a4d-aa52-6bff58c57489)

_Test 8_
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Verify that there is a field at the bottom named "Diet"

_Test 9_
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "Gluten Free"
This means no wheat or gluten containing foods
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are gluten free meals
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were gluten free

_Test 10_ 
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "Ketogenic"
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are Ketogenic meals. This means relatively low carbohydrates 
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were Ketogenic

_Test 11_ 
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "Vegetarian"
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are Vegetarian meals. This means no meat products, but dairy and eggs are okay
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were Vegetarian

_Test 12_ 
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "Vegan"
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are Vegetarian meals. This means no meat products or ANY animal based products. So no eggs or Dairly
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were Vegan

_Test 13_ 
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "None"
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are a verity of meals with no dietary restrictions
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were non restricted

**Comment by Nildham21** [comment]
Add tests

**Comment by Nildham21** [comment]
Test 2 is not relevant, you can remove that test

**Comment by Nildham21** [comment]
Attempted to login with username j and password string, and I receive the following message "Please Enter Valid Username and Password". Please provide different account credentials
