### ISSUE TITLE
Support changing profile picture on profile page

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#93]
**Task Tests**

_Test 1_
1) Go to [our webapp](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators)
2) Login with username: `sib` and password: `password`
3) Click on `Profile` on the navbar
4) Click on the `Edit Profile` Button at the bottom of the page
5) Click `Browse` and select a png, or jpeg *NOT JPG* file under 5MB from your computer
6) After selecting a picture, click `Update Profile Picture`
7) Verify your new profile picture is now displayed

**Comment by Nildham21** [comment]
The button to select an image is called "Choose file" not "Browse", please update this in step 5
