### ISSUE TITLE
Meal recommendations customizing cuisines 

### ISSUE THREAD

**Issue by JakeGuzzardo** [cse442-at-ub/project_s23-the-ai-violators#94]
__Task Tests__

_Test 1_
1) go to our [login page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Click on Sign up and create an account with the following info.
Email: TestUser2023@gmail.com
username: TestUser2023
password: string
confirm Password: string
3) Click the back to login prompt
4) Enter the following Credentials and click login
username: TestUser2023
password: string
5) At the one time survey page enter the following info:
Age: 21
Sex: Male
Height: 70
weight: 150
Select your goal: Maintain
Macro nutrient focus: Proteins
Activity Level: Moderately active
6) Press Get started
7) Verify that you are brought to the content page![homepage.png](https://images.zenhubusercontent.com/63e403ef8830c2dab4af86f9/a323b9cc-e8db-4a4d-aa52-6bff58c57489)

_Test 2_
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Verify that there is a field at the bottom named "Diet"

_Test 3_
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "Gluten Free"
This means no wheat or gluten containing foods
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are gluten free meals
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were gluten free

_Test 4_ 
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "Ketogenic"
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are Ketogenic meals. This means relatively low carbohydrates 
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were Ketogenic

_Test 5_ 
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "Vegetarian"
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are Vegetarian meals. This means no meat products, but dairy and eggs are okay
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were Vegetarian

_Test 6_ 
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "Vegan"
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are Vegetarian meals. This means no meat products or ANY animal based products. So no eggs or Dairly
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were Vegan

_Test 7_ 
1) If you have not completed test 1 complete test 1
2) Click on "Profile" on the navigation bar to access the profile page
3) Click Edit Profile
4) Select the drop down corresponding with "Diet" and select "None"
5) Click save changes
6) Click the "Meals" tab on the Navigation bar on the top of the screen
7) Verify that all meals Recommended are a verity of meals with no dietary restrictions
8) Refresh the page
9) Complete steps 7 and 8 3 times
10) Verify all meals recommended were non restricted

**Comment by Nildham21** [comment]
Missing user story dependency
