### ISSUE TITLE
Update file failed to upload error message

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#95]
**Task Tests**

_Test 1_
1) Go to [our webapp](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators)
2) Login with username: `sib` and password: `password`
3) Click on `Profile` on the navbar
4) Click on the `Edit Profile` Button at the bottom of the page
5) Click `Browse` and select a non png, jpg, or jpeg file. It may be useful to create an empty txt file to use for this
6) Verify the error message says `An error occured. Only JPEG or PNG (not JPG) images under 5MB may be submitted`.

**Comment by Nildham21** [comment]
Its change the way step 6 is written, "Verify the error message sufficiently explains that the file type could be wrong" instead of assuming, state the exact message that the user should view
