### ISSUE TITLE
Recalculate Calories when user info changes

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#96]
**Task Tests**

_Test 1_
1) Go to [our webapp](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/)
2) Login with username: `Chad` and password: `password`
3) Click on profile in the navbar
4) Make a note of the current calorie goal
4) Click on edit profile
5) Change the weight to 250, then click save changes
6) Verify the calorie goal is different, make a note of this new goal
7) Click on edit profile
8) Change sex to female
9) Verify the calorie goal is different, make a note of this new goal
10) Click on edit profile
11) Change height to 60
12) Verify the calorie goal is different, make a note of this new goal
13) Click on edit profile
14) Change activity level to Professional Athlete
15) Verify the calorie goal is different

**Comment by Nildham21** [comment]
The following test verifies that the current calorie goal changes when weight is changed. Can you add tests to verify that when sex, height, and activity level are changed the current calorie goal should change as well
