### ISSUE TITLE
Update navbar Meal tab and username

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#97]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/a62beb40-a2ba-4252-8517-a7ec906546ba)
3. Verify that the username "cam" is display on the bar at the top of the screen and that it is a different font from the rest of the words in the bar
3. Click the username text "cam" on the header bar and verify you are moved to the profile page:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/a38975bd-342b-4ccc-890f-ab9b62b04455)

**Comment by Nildham21** [comment]
Need to add task tests and dependency
