### ISSUE TITLE
Update macro colors on content page

### ISSUE THREAD

**Issue by cameronheffler** [cse442-at-ub/project_s23-the-ai-violators#98]
**Task Tests**

_Test 1_

1. Go to our [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/login/)
2. Login in with the test username "cam" and password "camtest" and verify you were redirected to the Content Page: ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/a5358846-6bdb-476b-bc75-964e09f89cc9)
3. Click the text "Track Page" on the header bar and verify you are there:![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/b530e380-3f59-431d-a7f8-13929f89a693)
4. Enter todays into the Date field
5. Enter "steak" into the Meal field
6. Enter "400" into the Calories field
7. Enter "10" into the Carbs field
8. Enter "20" into the Protein field
9. Enter "30" into the Fats field
10. Click the blue "Add" button at the bottom of the screen
11. Click the text "Content" on the header bar and verify you are there ![image.png](https://images.zenhubusercontent.com/63e40455b83e4f3651d91e75/669f6387-e37f-459e-a197-2a9312045bf1)
12. Verify the text "20 / 167" is red and correlates to the red protein part of the ring
13. Verify the text "10 / 253.625" is blue and correlates to the blue carbs part of the ring
14. Verify the text "30 / 66.8" is yellow and correlates to the yellow fats part of the ring

**Comment by Nildham21** [comment]
Need to add task tests and user story dependency

**Comment by Nildham21** [comment]
Can you update the picture for step 2 so the macro colors are shown as well

**Comment by Nildham21** [comment]
Need to user story dependency still
