### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by sebastianrich18** [cse442-at-ub/project_s23-the-ai-violators#99]
**Task Tests**

_Test 1_
1) Go to [our webapp](https://www-student.cse.buffalo.edu/CSE442-542/2023-Spring/cse-442g/project_s23-the-ai-violators/public/profile/)
2) In the tab of your browser, verify the carrot icon shows

**Comment by Nildham21** [comment]
Each task we create needs to be part of a user story, however, this task does not fall under any of the current user stories that we have written. Please create a new user story  along the lines of "As a user of nutr.io I want the application logo to appear on the browser tab so I can tell which tabs are on the nutr.io site"

**Comment by Nildham21** [comment]
The carrot only appears on the signup and login pages, on every other page it goes back to UB logo
